### ISSUE TITLE
Running SPA per service

### ISSUE THREAD

**Issue by firdiansyah26** [jualoppaz/single-spa-login-example-with-npm-packages#13]
Hi @jualoppaz, i want to ask about, how to I develop SPA per service like example your project. So I can running only for React page, Vue page, etc? Thank you

**Comment by jualoppaz** [comment]
Hi @firdiansyah26 ! As I am currently used to VueJS I can confirm you that running a microfrontend by its own without other single-spa applications.

For example, in the [Vue packaje.json file](https://github.com/jualoppaz/single-spa-vue-app/blob/master/package.json) you could define another script like this:

```
"scripts": {
    ...
    "local": "vue-cli-service serve src/main.js",
  },
```

And you could run your microfrontend with `npm run local` command, and you can also skip the entrypoint param as is the default value.

You only have to create a standard **main.js** file for any **vue-cli** project. I suppose that you could achieve the same mechanism with **React**, but I'm not sure if **Angular** provides an easy way of doing this because of **builders**.

I recommend you to take a look to every **single-spa** repos and ask for this matter in the official repositories.

Hope this guidelines be useful for you.
