### ISSUE TITLE
Can we have AngularJS/Vue/React without using as libraries?

### ISSUE THREAD

**Issue by ajaykumarsana** [jualoppaz/single-spa-login-example-with-npm-packages#7]
HI @jualoppaz ,

Is it possible to have [this](https://github.com/jualoppaz/single-spa-home-app) code integrated into main repo without using npm libraries?

Can you please help?
Thanks a lot.

**Comment by ajaykumarsana** [comment]
Hi @jualoppaz ,
Can you please help?

Thanks a lot.

**Comment by jualoppaz** [comment]
Hi @ajaykumarsana ! Sorry for the late response 🙏

Of course, the strategy you are asking for is the first and easier one that single-spa proposes. You can see details [here](https://single-spa.js.org/docs/separating-applications#option-1-one-code-repo-one-build).

You can move all webpack config for [single-spa-home-app](https://github.com/jualoppaz/single-spa-home-app) to your unique webpack.config.js file in your mono repo.

The matter you must consider is be careful of not mixing config between modules and technologies. If all of your micro frontends are made with the same technology (in this case AngularJS) it could be a great solution. However, if you pretend to use different technologies in your microfrontends, having all configs in a unique webpack.config.js could be a nightmare.

I recommend you an example like this: https://github.com/single-spa/single-spa-examples/blob/master/webpack.config.js

This example is not recommended currently by Joel Denning because single-spa has been improved a lot from this example was created, but you can see there a strategy for manage several microfrontends with different technologies and custom config.

Hope this guidelines help you!
